$schema: https://json-schema.org/draft/2020-12/schema
$id: https://schemas.goneat.dev/security-policy/v1.0.0
$version: 1.0.0
title: Goneat Security Policy Schema
description: Schema for security policy configuration including suppression rules and enforcement
type: object
properties:
  $schema:
    type: string
    description: JSON Schema reference for this policy file
    format: uri
    examples:
      - https://schemas.goneat.dev/security-policy/v1.0.0
  security:
    type: object
    description: Security policy configuration
    properties:
      suppressions:
        type: object
        description: Configuration for security suppression handling
        properties:
          track:
            type: boolean
            description: Whether to track suppressions in output
            default: true
          report_metrics:
            type: boolean
            description: Include suppression metrics in reports
            default: true
          require_reason:
            type: array
            description: Rules for when suppression reasons are required
            items:
              type: object
              properties:
                severity:
                  type: array
                  description: Severity levels that require reasons
                  items:
                    type: string
                    enum: [critical, high, medium, low, info]
                tools:
                  type: array
                  description: Specific tools that require reasons
                  items:
                    type: string
                    examples: [gosec, bandit, semgrep]
              additionalProperties: false
          max_age_days:
            type: integer
            description: Maximum days before suppression review required
            minimum: 1
            maximum: 365
            default: 90
          require_approval:
            type: array
            description: Rules for when suppressions need approval
            items:
              type: object
              properties:
                severity:
                  type: array
                  description: Severity levels requiring approval
                  items:
                    type: string
                    enum: [critical, high, medium, low, info]
                rules:
                  type: array
                  description: Specific rule IDs requiring approval
                  items:
                    type: string
                    examples: [G304, G204, B104]
                approvers:
                  type: array
                  description: GitHub handles of required approvers
                  items:
                    type: string
                    pattern: "^@[a-zA-Z0-9-]+$"
                    examples: ["@security-team", "@arch-eagle"]
              required: [approvers]
              additionalProperties: false
          allowed_reasons:
            type: array
            description: Predefined allowed suppression reasons
            items:
              type: string
            examples:
              - "Input validated in middleware"
              - "Test fixture only"
              - "False positive - static string"
              - "Legacy code - tracked in JIRA"
              - "Performance critical path"
        additionalProperties: false
      enforcement:
        type: object
        description: Security enforcement rules
        properties:
          fail_on:
            type: string
            description: Default failure threshold
            enum: [critical, high, medium, low, info]
            default: high
          by_environment:
            type: object
            description: Environment-specific enforcement
            additionalProperties:
              type: object
              properties:
                fail_on:
                  type: string
                  enum: [critical, high, medium, low, info]
                max_suppressions:
                  type: integer
                  minimum: 0
                block_new_suppressions:
                  type: boolean
                  default: false
              additionalProperties: false
            examples:
              - production:
                  fail_on: high
                  max_suppressions: 10
                  block_new_suppressions: true
              - development:
                  fail_on: medium
                  max_suppressions: 100
          max_total_suppressions:
            type: integer
            description: Maximum total suppressions allowed
            minimum: 0
          block_patterns:
            type: array
            description: Patterns that should never be suppressed
            items:
              type: object
              properties:
                rule:
                  type: string
                  description: Rule ID pattern
                  examples: ["G401", "B301"]
                file_pattern:
                  type: string
                  description: File glob pattern
                  examples: ["**/auth/**", "**/crypto/**"]
                message:
                  type: string
                  description: Error message when blocked
              required: [rule, message]
              additionalProperties: false
        additionalProperties: false
    required: [suppressions]
    additionalProperties: false
additionalProperties: false
required: [security]
examples:
  - security:
      suppressions:
        track: true
        report_metrics: true
        require_reason:
          - severity: [critical, high]
        max_age_days: 90
        require_approval:
          - severity: [critical]
            approvers: ["@security-team", "@arch-eagle"]
        allowed_reasons:
          - "Input validated in middleware"
          - "Test fixture only"
          - "False positive"
      enforcement:
        fail_on: high
        by_environment:
          production:
            fail_on: high
            max_suppressions: 10
            block_new_suppressions: true
          development:
            fail_on: medium
        block_patterns:
          - rule: "G401"
            file_pattern: "**/crypto/**"
            message: "MD5/SHA1 cannot be suppressed in crypto packages"
