# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md
self-hosted-runner:
  labels:
    - ubuntu-latest-x64-m
    - ubuntu-latest-arm64-m
    - windows-latest-arm64-s
