package sbom

import (
	"encoding/json"
	"fmt"
	"os"
)

func CountCycloneDXPackagesFromFile(path string) (int, error) {
	data, err := os.ReadFile(path) // #nosec G304 - path is the SBOM output file generated by goneat itself (sbom/ directory), not derived from user-controlled input
	if err != nil {
		return 0, fmt.Errorf("read sbom: %w", err)
	}
	var cdx struct {
		Components []interface{} `json:"components"`
	}
	if err := json.Unmarshal(data, &cdx); err != nil {
		return 0, fmt.Errorf("parse cyclonedx sbom: %w", err)
	}
	return len(cdx.Components), nil
}
