$schema: https://json-schema.org/draft/2020-12/schema
$id: https://schemas.goneat.dev/config/v1.0.0
$version: 1.0.0
title: Goneat Configuration Schema
description: Configuration schema for Goneat, the unified Go-based formatting and validation tool
type: object
properties:
  $schema:
    type: string
    description: JSON Schema reference for this configuration file
    format: uri
    examples:
      - https://schemas.goneat.dev/config/v1.0.0
  format:
    type: object
    description: Formatting configuration for different file types
    properties:
      go:
        type: object
        description: Go code formatting options
        properties:
          simplify:
            type: boolean
            description: Enable code simplification using gofmt's -s flag
            default: true
            examples:
              - true
              - false
        additionalProperties: false
        required: []
      yaml:
        type: object
        description: YAML formatting options
        properties:
          indent:
            type: integer
            description: Number of spaces for indentation
            minimum: 2
            maximum: 8
            default: 2
            examples:
              - 2
              - 4
          line_length:
            type: integer
            description: Maximum line length before wrapping
            minimum: 60
            maximum: 200
            default: 80
            examples:
              - 80
              - 120
          quote_style:
            type: string
            description: Quote style for strings
            enum:
              - single
              - double
            default: double
            examples:
              - double
              - single
          trailing_newline:
            type: boolean
            description: Add trailing newline at end of file
            default: true
            examples:
              - true
              - false
        additionalProperties: false
        required: []
      json:
        type: object
        description: JSON formatting options
        properties:
          indent:
            type: string
            description: Indentation string (spaces or tab)
            pattern: '^(\\s+|\\t)$'
            default: "  "
            examples:
              - "  "
              - "    "
              - "\t"
          compact:
            type: boolean
            description: Output compact JSON instead of pretty-printed
            default: false
            examples:
              - false
              - true
          sort_keys:
            type: boolean
            description: Sort object keys alphabetically
            default: false
            examples:
              - false
              - true
          trailing_newline:
            type: boolean
            description: Add trailing newline at end of file
            default: true
            examples:
              - true
              - false
        additionalProperties: false
        required: []
      markdown:
        type: object
        description: Markdown formatting options
        properties:
          line_length:
            type: integer
            description: Maximum line length before wrapping
            minimum: 60
            maximum: 200
            default: 80
            examples:
              - 80
              - 120
          trailing_spaces:
            type: boolean
            description: Remove trailing spaces from lines
            default: false
            examples:
              - false
              - true
          reference_style:
            type: string
            description: Style for link references
            enum:
              - collapsed
              - full
              - shortcut
            default: collapsed
            examples:
              - collapsed
              - full
          code_block_style:
            type: string
            description: Style for code blocks
            enum:
              - fenced
              - indented
            default: fenced
            examples:
              - fenced
              - indented
        additionalProperties: false
        required: []
    additionalProperties: false
    required: []
additionalProperties: false
required: []
